import { chooseOption } from "./fixtures/fields";
import { expect, test, type Page } from "@playwright/test";
import type { ReviewJob } from "../packages/ui/src/components/review-assistant";
import { mockWorkspace } from "./fixtures/workspace";
const group = "6d5bbc8f-9e97-42b9-af07-3a9da4c12518";
const report = { summary: "Ship identity with verified sessions.", findings: [{ severity: "high", detail: "Protected routes need verified sessions.", evidence: ["src/auth.ts"] }], scope: "Add signed sessions and protected routes.", acceptance: "Verify login, logout and protected access.", assumptions: "Source sample only. Workflows still need verification.", questions: ["Which identity provider?"], effort: { minHours: 8, maxHours: 16, confidence: "low" } };
const pair = (id = group): ReviewJob[] => ["codex", "claude"].map((provider, i) => ({ id: `${id}-${provider}`, comparisonId: id, provider, status: "SUCCEEDED", errorCode: null, commit: "a".repeat(40), createdAt: "2026-10-07T12:00:00Z", stale: false, inputDigest: "current", instructions: "Estimate identity scope.", result: { ...report, scope: `${provider} scope: ${report.scope}`, effort: { ...report.effort, minHours: 8 + i * 4, maxHours: 16 + i * 8 } }, coverage: { readFiles: 3, eligibleFiles: 7, limitations: ["Static sample."] } }));
async function setup(page: Page) {
  const state = await mockWorkspace(page, { operator: true });
  state.project.stage = "IN_REVIEW"; state.project.aiReviewConsentAt = new Date().toISOString(); state.project.repositoryUrl = "https://github.com/builder/private-app";
  return state;
}
test("compares independent proposals with shared cost settings and chooses an editable scope", async ({ page }, info) => {
  const state = await setup(page); let jobs: ReturnType<typeof pair> = [], comparisonId = group;
  const bodies: Record<string, unknown>[] = [];
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs, onlineWorkers: 1, evidenceDigest: "current" } }));
  await page.route("**/review-comparisons/*", route => route.fulfill({ json: { id: comparisonId, jobs } }));
  await page.route("**/review-comparisons", route => {
    const body = route.request().postDataJSON(); bodies.push(body); comparisonId = body.id; jobs = pair(comparisonId); state.project.version++;
    return route.fulfill({ json: { id: body.id, jobs: jobs.map(({ id, provider }) => ({ id, provider })) } });
  });
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`);
  await chooseOption(page.getByLabel("Coding agent"), "both");
  await page.getByLabel("Follow-up question or review instructions (optional)").fill("Compare the minimum launch scope.");
  await page.getByRole("button", { name: "Compare proposals", exact: true }).click();
  const comparison = page.getByRole("region", { name: "Proposal comparison" });
  await expect(comparison.getByRole("article", { name: "Codex proposal" })).toContainText("8–16 engineering hours");
  await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("12–24 engineering hours");
  expect(bodies).toHaveLength(1); expect(bodies[0]).toMatchObject({ provider: "both", instructions: "Compare the minimum launch scope." }); expect(bodies[0]).not.toHaveProperty("parentJobId");
  await page.getByText("Plan cost & working time", { exact: true }).click(); await page.getByLabel("Your hourly rate").fill("100");
  await expect(comparison.getByRole("article", { name: "Codex proposal" })).toContainText("$960–$1,920");
  await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("$1,440–$2,880");
  await comparison.getByRole("button", { name: "Add Codex scope to draft" }).click();
  await comparison.getByRole("button", { name: "Add Claude scope to draft" }).click();
  await expect(page.locator("textarea[name=scope]")).toHaveValue(`codex scope: ${report.scope}\n\nclaude scope: ${report.scope}`);
  await expect(page.locator("input[name=amount]")).toHaveValue(""); expect(state.project.proposals).toHaveLength(0); expect(state.project.reviewSummary).toBeNull();
  const cards = comparison.getByRole("article");
  const boxes = await cards.evaluateAll(els => els.map(el => ({ x: el.getBoundingClientRect().x, y: el.getBoundingClientRect().y })));
  if (info.project.name === "mobile") expect(boxes[1]!.y).toBeGreaterThan(boxes[0]!.y); else expect(boxes[1]!.x).toBeGreaterThan(boxes[0]!.x);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await comparison.screenshot({ path: info.outputPath(`comparison-${info.project.name}.png`) });
});
test("preserves a completed proposal while Claude waits, cancels unfinished work and handles stale evidence", async ({ page }) => {
  const state = await setup(page), jobs = pair(); jobs[1]!.status = "QUEUED"; jobs[1]!.result = null;
  let digest = "current", cancelled = 0;
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs, onlineWorkers: 1, evidenceDigest: digest } }));
  await page.route("**/review-comparisons/*", route => route.fulfill({ json: { jobs } }));
  await page.route("**/review-comparisons/*/cancel", route => { cancelled++; jobs[1]!.status = "CANCELLED"; return route.fulfill({ json: { saved: true } }); });
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`);
  const comparison = page.getByRole("region", { name: "Proposal comparison" });
  await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("own subscription login");
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeEnabled();
  await expect(comparison.getByRole("button", { name: "Continue with Claude" })).toBeDisabled();
  await page.getByRole("button", { name: "Cancel unfinished comparison" }).click(); expect(cancelled).toBe(1);
  await page.reload(); await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("Cancelled");
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeEnabled();
  digest = "changed"; await page.reload();
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeDisabled();
  await expect(comparison.getByRole("button", { name: "Continue with Claude" })).toBeDisabled();
  expect(state.project.proposals).toHaveLength(0);
});
test("hands either proposal to the other agent, preserves selected context and clears it for an independent comparison", async ({ page }) => {
  const state = await setup(page), jobs = pair();
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs, onlineWorkers: 1, evidenceDigest: "current" } }));
  await page.route("**/review-comparisons/*", route => route.fulfill({ json: { jobs } }));
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`);
  const comparison = page.getByRole("region", { name: "Proposal comparison" });
  for (const [from, to, provider] of [["Codex", "Claude", "claude"], ["Claude", "Codex", "codex"]]) {
    await comparison.getByRole("article", { name: `${from} proposal` }).getByRole("button", { name: `Continue with ${to}` }).click();
    await expect(page.getByLabel("Coding agent")).toHaveAttribute("data-value", provider!);
    await expect(page.getByLabel("Follow-up question or review instructions", { exact: true })).toBeFocused();
    await page.getByLabel("Follow-up question or review instructions", { exact: true }).fill(`Challenge ${from} assumptions.`);
    await page.reload();
    const saved = await page.evaluate(({ projectId }) => JSON.parse(sessionStorage.getItem(`m8-workspace-draft:customer:review-session:${projectId}`)!), { projectId: state.project.id });
    expect(saved.parentJobId).toBe(`${group}-${from!.toLowerCase()}`); expect(saved.provider).toBe(provider);
  }
  await chooseOption(page.getByLabel("Coding agent"), "both");
  await expect(page.getByRole("button", { name: "Compare proposals", exact: true })).toBeEnabled();
  expect(await page.evaluate(({ id }) => JSON.parse(sessionStorage.getItem(`m8-workspace-draft:customer:review-session:${id}`)!).parentJobId, { id: state.project.id })).toBeNull();
});
test("reconciles a lost comparison response after reload even when both jobs are outside latest history", async ({ page }) => {
  const state = await setup(page); let saved: Record<string, unknown> | null = null, posted = 0;
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs: [], onlineWorkers: 1, evidenceDigest: "current" } }));
  await page.route("**/review-comparisons", route => { saved = route.request().postDataJSON(); posted++; state.project.version++; return route.abort("connectionreset"); });
  await page.route("**/review-comparisons/*", route => saved ? route.fulfill({ json: { id: saved.id, jobs: pair(saved.id as string) } }) : route.fulfill({ status: 404, json: { error: { message: "Not saved yet." } } }));
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`); await chooseOption(page.getByLabel("Coding agent"), "both");
  await page.getByRole("button", { name: "Compare proposals", exact: true }).click();
  await expect(page.getByRole("button", { name: "Retry queue request" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("region", { name: "Proposal comparison" }).getByRole("button", { name: "Add Claude scope to draft" })).toBeEnabled();
  await expect(page.getByRole("button", { name: "Retry queue request" })).toHaveCount(0); expect(posted).toBe(1);
});
test("a failed group lookup blocks duplicates and an exact retry retains the original instructions", async ({ page }) => {
  const state = await setup(page); const bodies: Record<string, unknown>[] = []; let failLookup = true;
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs: [], onlineWorkers: 1 } }));
  await page.route("**/review-comparisons", route => { bodies.push(route.request().postDataJSON()); return route.abort("connectionreset"); });
  await page.route("**/review-comparisons/*", route => route.fulfill({ status: failLookup ? 500 : 404, json: { error: { message: failLookup ? "Comparison lookup temporarily unavailable." : "Not saved." } } }));
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`); await chooseOption(page.getByLabel("Coding agent"), "both");
  await page.getByLabel("Follow-up question or review instructions (optional)").fill("Only minimum launch scope.");
  await page.getByRole("button", { name: "Compare proposals", exact: true }).click(); await page.reload();
  await expect(page.getByRole("button", { name: "Retry queue request" })).toBeDisabled();
  await expect(page.locator(".review-assistant").getByRole("alert")).toContainText("Comparison lookup temporarily unavailable."); expect(bodies).toHaveLength(1);
  failLookup = false; await page.locator(".review-assistant").getByRole("button", { name: "Try again", exact: true }).click();
  await page.getByRole("button", { name: "Retry queue request" }).click();
  expect(bodies).toHaveLength(2); expect(bodies[1]).toEqual(bodies[0]);
});
test("a comparison survives an expired session only for its original operator account", async ({ page }) => {
  const state = await setup(page); let saved: Record<string, unknown> | null = null, posts = 0;
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs: [], onlineWorkers: 1 } }));
  await page.route("**/review-comparisons/*", route => route.fulfill({ status: 404, json: { error: { message: "No saved comparison." } } }));
  await page.route("**/review-comparisons", route => { saved = route.request().postDataJSON(); posts++; state.signedOut = true; return route.fulfill({ status: 401, json: { error: { message: "Sign in again; the pending comparison is saved." } } }); });
  const url = `http://127.0.0.1:3131/?project=${state.project.id}`;
  await page.goto(url); await chooseOption(page.getByLabel("Coding agent"), "both"); await page.getByLabel("Follow-up question or review instructions (optional)").fill("Compare the launch plan.");
  await page.getByRole("button", { name: "Compare proposals", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Sign in to the backoffice.", exact: true })).toBeVisible();
  state.signedOut = false; state.accountId = "other-operator"; await page.goto(url);
  await expect(page.getByLabel("Coding agent")).toHaveAttribute("data-value", "codex"); await expect(page.getByRole("button", { name: "Retry queue request" })).toHaveCount(0);
  state.accountId = "customer"; await page.goto(url);
  await expect(page.getByLabel("Coding agent")).toHaveAttribute("data-value", "both");
  await expect(page.getByRole("button", { name: "Retry queue request" })).toBeEnabled();
  const pending = await page.evaluate(({ id }) => JSON.parse(sessionStorage.getItem(`m8-workspace-draft:customer:review-session:${id}`)!).pending, { id: state.project.id });
  expect(pending).toEqual(saved); expect(posts).toBe(1);
});
test("a failed partner keeps its useful reply, and comparison status errors require reconciliation before importing", async ({ page }) => {
  await page.clock.install();
  const state = await setup(page), jobs = pair(); let unavailable = false;
  jobs[1]!.status = "FAILED"; jobs[1]!.result = null; jobs[1]!.errorCode = "QUOTA";
  await page.route("**/review-jobs", route => route.fulfill({ json: { jobs, onlineWorkers: 1, evidenceDigest: "current" } }));
  await page.route("**/review-comparisons/*", route => unavailable ? route.fulfill({ status: 503, json: { error: { message: "Comparison status unavailable." } } }) : route.fulfill({ json: { jobs } }));
  await page.goto(`http://127.0.0.1:3131/?project=${state.project.id}`);
  const comparison = page.getByRole("region", { name: "Proposal comparison" });
  await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("Subscription limit reached");
  await expect(comparison.getByRole("article", { name: "Claude proposal" })).toContainText("Any completed proposal remains available.");
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeEnabled();
  unavailable = true;
  await page.clock.fastForward(10_001);
  await expect(comparison.getByRole("alert")).toContainText("Comparison status unavailable.");
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeDisabled();
  unavailable = false; await comparison.getByRole("button", { name: "Retry comparison status" }).click();
  await expect(comparison.getByRole("button", { name: "Add Codex scope to draft" })).toBeEnabled();
});
